### ISSUE TITLE
Remove Paranamer dependency  from orika core project

### ISSUE THREAD

**Issue by rajcspsg** [orika-mapper/orika#268]
Hi,

We don't need com.thoughtworks.paranamer dependency as java has inbuilt functionality for it.

We are using couple for opensource libraries and easy brings its own paranamer and it causes ClassNotFoundException.

**Comment by 123Haynes** [comment]
@rajcspsg I agree.  
I originally wanted to remove it when I updated the orika dependencies in my last PRs, 
but replacing it was more complex than I thought and I didn't have the time to dive into it.  :(

**Comment by rajcspsg** [comment]
ohh I see. I will give it a try and see but I can't really commit any timeline.

**Comment by elaatifi** [comment]
Actually this is not possible since the feature is just an opt-in (mean that you need to enable to some flags on javac compiler)

**Comment by 123Haynes** [comment]
@elaatifi can you eloborate that a bit please?

All paranamer does is this:
"It is a library that allows the parameter names of non-private methods and constructors to be accessed at runtime."

Java comes with a built in funtionality for this since Java 8, so it should be possible to replace this old dependency without loosing any functionality.  

It even says so on the paranamer github page...
https://github.com/paul-hammant/paranamer#java8-has-parameter-name-access-built-in

**Comment by elaatifi** [comment]
`the source needs to be compiled with the javac command line option -parameters in order to add the meta data for parameter name reflection to the class file.`

But an Orika user may need to map code without having access to the source.

**Comment by elaatifi** [comment]
Maybe in the future we will make paranamer optional and rely only on reflection but for now this is not practical I think.

**Comment by 123Haynes** [comment]
>But an Orika user may need to map code without having access to the sources.
Also this option is not enabled by default.

oooh i see. I missed that even the users of orika would need to use this. Sorry!
