### ISSUE TITLE
Fail on purpose if mapping is incomplete

### ISSUE THREAD

**Issue by fralalonde** [orika-mapper/orika#291]
As it is, Orika is pretty loose with mappings, using a best-effort strategy to map fields. This makes it easy to start using it and get good results. 

In more complex scenarios, it would be beneficial to have some form of "strict mode" that would require that all fields to be mapped unless explicitly marked as "ignored" or "optional". Obviously, this mode would be opt-in to preserve compatibility. When enabled, mapper generation would `throw` if the mapping is incomplete.
 
I believe this would be a _major_ safety enhancement as it would allow catching otherwise insidious bugs introduced by contract changes or refactoring.

Note, if this is already possible, it should be documented better as I scoured trough the manual and couldn't find it.

**Comment by fralalonde** [comment]
Also, if combined with compile-time generation as suggested in #245, this would allow compile-time validation of mapping completeness.

**Comment by elaatifi** [comment]
Actually there was a feature like this in the past and has been dropped (due to the initial implementation that needed a lot of work for the developer using Orika) the main objective of this project is help get past too much ceremonies related to mapping.

I agree with you that in some scenario it can be very useful to enforce policies. This is possible but need  to provide a custom ClassMapBuilder that validate it self against (list of properties from Class A & B) to verify if any field has been left behind (using the collection of the field maps)

**Comment by fralalonde** [comment]
👍
