### ISSUE TITLE
(1.4.6) Invalid code generated when embedded field name not a valid java variable name

### ISSUE THREAD

**Issue by StuSchrader** [orika-mapper/orika#77]
I am experiencing a code generation problem when embedded field map key is not a valid java identifier.

For example, if I map between two classes:

    Class A {
        private Map<String, List<String>> mapSource;
    }

    Class B {
        private Set<String> targetSet;
    } 

as:

    mapperFactory.classMap(A.class, B.class).field("mapSource['foo//bar']", "targetSet").register(); 

The java created attempts to make use of the key name as a variable in the mapBtoA. That generates something along the lines of:

    ...
    if (!(((java.util.Set) source.getTargetSet()) == null)) {
	      java.util.List new_foo//bar = ((java.util.List)new java.util.ArrayList(((java.util.Set)source.getTargetSet()).size()));

	      new_foo//bar.addAll(mapperFacade.mapAsList(((java.util.Set)source.getTargetSet()), ((ma.glasnost.orika.metadata.Type)usedTypes[0]), ((ma.glasnost.orika.metadata.Type)usedTypes[0]), mappingContext));
        ((java.util.Map) destination.getMultiValues()).put("foo//bar", new_foo//bar);
    }
    ... 

It looks the the name used for the intermediate variable needs to scrubbed to be a valid java variable name when the code is generated.

**Comment by elaatifi** [comment]
Good catch !

**Comment by andreabertagnolli** [comment]
The issue is caused by method `name()` in class `VariableRef`.
When it's invoked to create generated code it returns the actual value but it doesn't always respect the java variable naming convention.

I think the best approach is to define a ne method called maybe `generatedVariableName()` that substitute the invalid characters of the `name()` with underscores or something like that.

What do you think?
