### ISSUE TITLE
Registering map with multiple converters does not work

### ISSUE THREAD

**Issue by yujungshen** [orika-mapper/orika#99]
When using date converter for 2 different formats for the same class but 2 different fields, this used to work for version 1.4.4, but since 1.4.5 it does not work anymore.  I am not sure if this is a new feature difference or not.  But I can see in the generated code that in 1.4.4 it can see 2 converters, and 1.4.6 the mapping code is generated with both field mapping using the first converters.

When I step into the code, in 1.4.5 and above versions, it shows only 1 converter in the converter factory. This feels like a breakage to me, but it's been 2 releases and no one seemed to notice it, I hope this is no intended?

Note that I've tried this in 1.4.5, 1.4.6 and also in the latest 1.5.0 beta, all have the same behavior.

[orika-date-mapping-test.zip](https://github.com/orika-mapper/orika/files/75238/orika-date-mapping-test.zip)

**Comment by andreabertagnolli** [comment]
The problem is in the UsedConvertersContext, because the equal method on DateToStringConverter is not overrided correctly.

One possible solution is to override that equal method, but the problem will be the same for every converter (and there are a lot of converters...)
The other solution will be to stop checking if converter is already registered and register every converter (transforming usedConvertes map to a list), I don't know if this will cause performance problems or something like that, but for sure will resolve every converter match problem.

Someone knows anything about this behaviour?
